name: Notify Slack on Push

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Send Slack Notification
      - name: Post message to Slack
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            :rocket: A new commit has been pushed to the main branch!
            *Repository*: ${{ github.repository }}
            *Branch*: ${{ github.ref_name }}
            *Commit Message*: ${{ github.event.head_commit.message }}
            *Committer*: ${{ github.event.head_commit.author.name }}
            *Commit URL*: ${{ github.event.head_commit.url }}
